### ISSUE TITLE
9.2.10《await foreach的使用准则》P275 示例代码，缺少async关键字、await关键字错误、Token拼写有多余空格、缩进建议

### ISSUE THREAD

**Issue by hihaojie** [nodew/framework-design-guidelines-cn-community#16]
P275、P276 示例代码，三处`await foreach`均错写为`async foreach`；

P275 示例代码，MaxAsync方法应使用`async`关键字标注，否则`await foreach`会报CS4032错误；

P275 示例代码，`cancellationTo Ken`中间出现了多余的空格：
```c#
async foreach (int value in source.WithCancellation(cancellationTo Ken).
ConfigureAwait(false))
```
另外，按照359页准则：
>DO 要为单个表达式的所有后续行添加一级缩进。

此处的`ConfigureAwait(false)`前建议添加缩进，即：
```c#
async foreach (int value in source.WithCancellation(cancellationTo Ken).
    ConfigureAwait(false)) {
    hasValue = true;
    ...
```

**Comment by nodew** [comment]
感谢指正，这里 `async foreach` 也是把原书的错误代码直接复制过来了，至于 `cancellationTo Ken` 这里是本来是换行，图书排版的时候被编辑合并成单行还加了空格。
